[package]
name = "stucco_common"
version = "0.1.0"
edition = "2024"

[features]
test = ["dissimilar"]

[dependencies]
hashbrown = { workspace = true, features = ["raw"]}
dissimilar = { version = "1.0.0", optional = true }

[dev-dependencies]
common = { workspace = true, features = ["test"] }
